### ISSUE TITLE
Tires should not be reflective

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#982] opened 2018-02-22 17:31 UTC
Tires should not be reflective as it makes them look metallic:

![fg](https://user-images.githubusercontent.com/5700795/36554136-3a325ce4-17f6-11e8-96cb-ff418cca5f17.jpg)

**Comment by wlbragg** [comment] 2018-02-22 19:56
Wow, OK kiddy's here is your lesson for the day.
I am relatively new to scene lighting as in I didn't know or care about the basics. Well now I do.

A long time ago I decided to do a JSBSim version of the Cub. The very first thing I did to the lighting effects was to get rid of the "specular fix" in the XML file. I did it because it mad the aircraft look like crap. I didn't know why. I didn't know what it was really doing. Yes I am an idiot. What it is doing is overriding all the lighting settings we assign to the mesh in Blender. Think about that. Every exterior model part is set to the exact same specular, diffuse, shininess setting and it looks like CRAP.
So, I need some help here. We have to either do away with the "specular fix" block in c172p.xml and allow the original blender settings (those in the .ac file) to take control. Or, we need to have many "specular fix" settings in the XML. Groups that are more appropriate for the object at hand.
 I got to tell you I am more than a little embarrassed that I didn't figure this out a year or two ago.

I'll post some images of the difference between where these two lighting control systems are sitting at this point in time. The we can go from there and decide what needs to be adjusted and by which system and by how much.

**Comment by HHS81** [comment] 2018-02-22 19:59
@wlbragg 
1) change the reflectionmap
or
2) change the material settings of the wheel (add an own material for)

**Comment by wlbragg** [comment] 2018-02-22 20:04
Sorry, I decided otherwise on my approach to this after looking at it a little farther. Pretend you didn't just see how dumb I really am! After looking a little closer I guess what was going on was originally the "specular fix" was intended to be just for the shinny surface areas of the fuselage and exterior part. I think other objects that should never have been added to it were. Many be me! Like I said, I basically just learned a very important lesson.
Let me remove the objects I think shouldn't be in the "specular fix" block and lets see where were at.

**Comment by HHS81** [comment] 2018-02-22 20:05
we had the same issue on the wheels of the dornier328. xcvb85 solved it anyhow.

**Comment by wlbragg** [comment] 2018-02-22 20:16
OK, we can make this as complicated or simple as we want.
My opinion...
First we need to look all the exterior objects and decide at what light settings each object looks best.
Ultimately these settings should be done in Blender (the .ac mesh) and not in the XML. Because, you can see it all together in Blender instead of guessing and having to adjust the XML and then see it in the sim to verify. Also because, why set a lighting setting in the .ac just to override it in the XML, makes no sense to me. Unless there is something else I am unaware of.
@HHS81 this somewhat applies to the material setting changes you apply to the instruments in the c182s. I think you should be using the .ac as designed and then the scene lighting can adjust accordingly. I get why your doing it, and if it is only a temporary fix, well then maybe. BUt ultimately the .ac should have the right light settings.

**Comment by HHS81** [comment] 2018-02-22 20:32
@wlbragg: the reasong doing it in .xml is, that you can change the material settings in runtime. Reflection and specular effects depends on the coating/ painting used. Every coating/ painting is different - so I can set it per livery.

**Comment by wlbragg** [comment] 2018-02-22 20:47
> so I can set it per livery.

Good to know, it looks like we don't change any lighting settings in our livery material setting blocks but I guess I see how you would do that and it make sense. But the original default livery shouldn't need that material change in the XML as far as I can tell.

@gilbertohasnofb 
Here is were were at with the tires. To do this right I should separate the rims from the tires, but I don't really want to have to go through the work of having to do that everywhere, the animations, effects, damage!
![fgfs-screen-010](https://user-images.githubusercontent.com/11069680/36563283-4390885e-17df-11e8-938c-3a4c88017e40.png)

**Comment by wlbragg** [comment] 2018-02-22 20:53
@gilbertohasnofb 
I'll push this so you can see it in the sim.

I change a few things on the exterior. Such as the following objects are now under the light settings of their .ac and not the specular fix.
TieDownTail
TieDownRight
TieDownLeft
TransponderAntenna
Antenna_ADF
Antenna_VOR
VHFAntenna
NoseWheel
LeftWheel
RightWheel
Axle

**Comment by gilbertohasnofb** [comment] 2018-02-22 20:58
> Here is were were at with the tires. To do this right I should separate the rims from the tires, but I don't really want to have to go through the work of having to do that everywhere, the animations, effects, damage!

Hmm, I see. If that's too much work then I guess we can live with it, but the structure that holds the tire looks quite different from the rest of the fuselage in that shot (the structure is nearly full white). In RL, this piece is actually metallic and very reflective, see:

![](https://www.flyingmag.com/sites/flyingmag.com/files/styles/655_1x_/public/import/2015/sites/all/files/_images/201504/Skyhawks-Reborn-Feature.jpg?itok=voshc5H5)

If you'd like, I can add a mettalic texture to one of the blank spaces in the default livery and we could map it. But it would be so pretty to have it shinny :wink: 

 > I'll push this so you can see it in the sim.

Cool, just let me know the branch

**Comment by wlbragg** [comment] 2018-02-22 21:05
>the structure that holds the tire looks quite different from the rest of the fuselage in that shot

That is a mistake on my part, I can fix that. I'm talking about the rim itself. It is going to get the same light settings as the tires unless we separate the rims from the tires into new object. I think we will have to do it whether I want to or not.

**Comment by wlbragg** [comment] 2018-02-22 21:12
>Cool, just let me know the branch

Unfortunately, it' going to be the existing branch for Create grain effect (dirt) #973
I'm making too many changes to the blend to be able to do it in another branch. We can eventually tie all affected issues to that PR. Maybe we should rename that PR as it initially had a blend change for the dirt effect but now it contains numerous changes to the blend for multiple issues? Working on the mesh does not make for a clean GIT session!

**Comment by wlbragg** [comment] 2018-02-22 21:33
If you want to make us a metallic texture in fuselage.png I'll use it for the front tire forks!

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:00
> That is a mistake on my part, I can fix that. I'm talking about the rim itself. It is going to get the same light settings as the tires unless we separate the rims from the tires into new object. 

It would be cool to apply the effect to the rims but that would just be a small detail, I am completely fine in leaving them as they are. But if you notice, in the photograph above this structure holding the front tire is quite different than what we have in the sim. Is that a case for remodelling it?

> Unfortunately, it' going to be the existing branch for Create grain effect (dirt)

No problems, I completely understand your reasoning. 

> If you want to make us a metallic texture in fuselage.png I'll use it for the front tire forks!

Will do that, give me a second.

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:02
More photographic references, all these below are model P's:

![](http://imgproc.airliners.net/photos/airliners/7/7/5/4843577.jpg?v=v4b6ffb15c0b)
![](http://imgproc.airliners.net/photos/airliners/5/2/9/4763925.jpg?v=v4c6c51cca0a)
![](http://imgproc.airliners.net/photos/airliners/1/5/0/4761051.jpg?v=v4b8f29e353d)

**Comment by wlbragg** [comment] 2018-02-22 22:15
Hold on, look at this.
![fgfs-screen-013](https://user-images.githubusercontent.com/11069680/36567277-88ed20cc-17eb-11e8-9ecc-8fb1e34ddf25.png)
![fgfs-screen-014](https://user-images.githubusercontent.com/11069680/36567282-8acdf4ac-17eb-11e8-8fd6-9cd669262507.png)

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:15
@wlbragg ok, done. See the texture below. Texture B should be used only for the shiny cylinder connecting the main tire hook to the aircraft. Texture A should be used for the hook itself and all other parts that aren't shiny in those references:

![fg](https://user-images.githubusercontent.com/5700795/36567253-c17b79ac-181d-11e8-8e49-54ef1ed7a65d.jpg)

Makes sense?

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:16
> Hold on, look at this.

Looks wonderful!

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:16
Make sure to test the model with the fairings.

**Comment by wlbragg** [comment] 2018-02-22 22:20
>Looks wonderful!

That is with existing texture

Let me do it with the new texture and see what it looks like and then we can decide.

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:21
> That is with existing texture

I know, I meant the model :wink:

**Comment by wlbragg** [comment] 2018-02-22 22:27
>Makes sense?

Yes

Can you post the same image as a png without the red markup so I can test it?

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:28
> Can you post the same image as a png without the red markup so I can test it?

I pushed it to the branch! See commit https://github.com/c172p-team/c172p-detailed/pull/973/commits/6e114d406303b7c044ca0690eaf7d9c0b370ef67

**Comment by wlbragg** [comment] 2018-02-22 22:30
>Make sure to test the model with the fairings.

It just now donned on me you think I redid the model. I didn't touch the model, just remapped the UV to a different part of the original texture, changed the lighting setting and the smoothing setting. Amazing what you can get away with.

**Comment by wlbragg** [comment] 2018-02-22 22:32
> I pushed it to the branch

OK, thanks. Should have something here shortly.

**Comment by wlbragg** [comment] 2018-02-22 22:45
![fgfs-screen-015](https://user-images.githubusercontent.com/11069680/36568462-b7b57022-17ef-11e8-8c0f-66acab293d57.png)
![fgfs-screen-016](https://user-images.githubusercontent.com/11069680/36568468-ba19b724-17ef-11e8-8fb2-42bc856d9193.png)

**Comment by wlbragg** [comment] 2018-02-22 22:50
Very nice!
![fgfs-screen-001](https://user-images.githubusercontent.com/11069680/36568653-6795cfc8-17f0-11e8-9727-3c64dd956277.png)
![fgfs-screen-002](https://user-images.githubusercontent.com/11069680/36568656-6a3e6032-17f0-11e8-9a11-48ba9327db46.png)

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:54
Much better indeed! But I am not sure if I am seeing things correctly but it seems that the bright cylinder is not fully mapped to the shiny metal texture (B in my reference). Compare this:

![fg](https://user-images.githubusercontent.com/5700795/36568806-44cc6118-1823-11e8-9a9d-0e7b17216887.jpg)

But perhaps that's just the screenshot.

**Comment by gilbertohasnofb** [comment] 2018-02-22 22:55
Blue is texture A (whitish matte metal) and red is texture B (shinny metallic texture for the cylinder)

**Comment by wlbragg** [comment] 2018-02-22 23:13
![fgfs-screen-003](https://user-images.githubusercontent.com/11069680/36569316-f7bbd23a-17f2-11e8-85c9-ba3b38632083.png)
Here is the bushkit mapped the same way to the new texture and with the new lighting settings and smoothness settings.
![fgfs-screen-006](https://user-images.githubusercontent.com/11069680/36569486-a58fd122-17f3-11e8-99e1-34b8cd9d71f9.png)

>bright cylinder is not fully mapped to the shiny metal texture

It is, change the angle your looking at it from. Change your view to below ground to change the angle the light reflects. It moves up the shaft.
![fgfs-screen-003](https://user-images.githubusercontent.com/11069680/36569507-bab1afc6-17f3-11e8-8076-b809bc613ca4.png)

**Comment by gilbertohasnofb** [comment] 2018-02-22 23:19
> It is, change the angle your looking at it from. Change your view to below ground to change the angle the light reflects. It moves up the shaft.

Yeah, I can see it now. Sorry it was just looking different from that angle. Thanks for mapping the textures, I guess this one is done.

**Comment by wlbragg** [comment] 2018-02-22 23:26
Yes, I added "Fixes #982" to PR.

**Comment by legoboyvdlp** [comment] 2018-02-23 00:46
Sorry, just a comment on an unrelated note, on the second image in the comment whrre wlbragg says the texture is "very nice" (as it is), the nose tire appears the be buried in the runway slightly?

**Comment by gilbertohasnofb** [comment] 2018-02-23 00:52
@legoboyvdlp I also noted that. Perhaps we should open a new issue for that, would you like to do that? You could add to it the screenshot that you mentioned.

**Comment by gilbertohasnofb** [comment] 2018-02-23 01:39
@wlbragg since you have lowered the shininess of the aircraft, would it be possible to raise it only for specific parts such as this new shiny metallic part of the landing gear structure? Or is it defined for the whole aircraft?

**Comment by wlbragg** [comment] 2018-02-23 02:28
Yes, as long as the object is standalone we can give it whatever we want.
Done!

**Closed** 2018-02-28 21:39 UTC
Labels: bug, effects
