### ISSUE TITLE
Pilot's eyes visible when changing views

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#109] opened 2015-03-26 14:17 UTC
When pressing v to change views from the cockpit to the outside view, the model of the pilot head is shown for a split second: http://i.imgur.com/Mm3XvAX.png

@Juanvvc wrote in the thread: "[...] the pilot's head and the eyes are hidden in the cockpit view, or you would only see what is inside your head! When you switch to an external view, in order to prevent some horror movie scene with a headless pilot, the head and the eyes are rendered again. As you noticed, there is a split second where head and eyes are visible but the external view is not ready yet. One way to fix this is using eyes with only single-side faces. I don't know why these models have two-sided faces."

**Comment by gilbertohasnofb** [comment] 2015-05-14 07:07
This was solved, wasn't it?

**Comment by Juanvvc** [comment] 2015-05-14 09:42
It is not. In any case, it is not a bug in the our project but in the walker. We can easily fix the bug by copying the model into our directory and defining the eyes as one-side surfaces, but I strongly believe the best solution is fixing the shared walker for all the community. There are many other little bugs in the female model that we fixed in our project related. I'm planing to submit these fixes to FGDATA.

**Comment by gilbertohasnofb** [comment] 2015-05-14 10:04
Ok, I don't have FG installed here and I didn't remember if this was still present. I changed the label from bug to enhancement then.

**Comment by onox** [comment] 2015-06-02 23:41
As @Juanvvc says, the shared walker should be fixed.

**Comment by wkitty42** [comment] 2015-06-03 02:24
i saw in an update earlier today or yesterday that there's a female walker... this is the one that i saw the eyes through when switching to the heli view... is this walker (pilot???) shared with other craft in fgfs or is it only for this craft??

**Comment by onox** [comment] 2015-06-03 09:15
I think shared. `c172p-set.xml` includes `Aircraft/Generic/Human/Include/walker-include.xml`.

**Comment by Juanvvc** [comment] 2015-06-03 10:38
It is shared, but the female model has many issues related to the position of her limbs. The xml file I submitted a few days ago fixes some of these issues. This file should be also submitted to FGDATA, but even if it is not accepted (or, most probably, I don't have the time to submit the file), our female model is already fixed.

This only fixed the position of her limbs, not the two-sided eyes. I could do the same with the eyes but I really prefer submitting a pull request to FGDATA instead of including the whole model in our repository.

**Comment by wkitty42** [comment] 2015-06-03 19:02
FWIW: i agree with your assessment, @Juanvvc

**Comment by onox** [comment] 2015-07-08 07:26
@Juanvvc Are you able to submit a PR to FGDATA this week?

**Comment by gilbertohasnofb** [comment] 2015-07-11 18:44
@onox maybe we should move this to the 3.8 release milestone.

**Comment by gilbertohasnofb** [comment] 2015-12-11 16:09
Since this still hasn't been fixed, what about using the male model for a while until the female model gets fixed? As much of a feminist as I am, those creepy eyes when moving the view are extremely disturbing :scream:

**Comment by onox** [comment] 2015-12-11 20:17
We just need to make the eyes a one-sided surface. See https://github.com/Juanvvc/c172p-detailed/issues/109#issuecomment-101986664

**Comment by gilbertohasnofb** [comment] 2015-12-11 20:18
I know that, my proposal was just a temporary fix while no one submits a patch to FGDATA.

**Comment by onox** [comment] 2015-12-11 20:18
@Juanvvc You made some fixes? Are those still local on your computer?

**Comment by gilbertohasnofb** [comment] 2018-02-25 17:02
It just came to my attention that @D-ECHO created a very good looking pilot model for the ASK-21 project, see: https://github.com/viktorradnai/flightgear-ask21/issues/140#issuecomment-368294291

**Comment by gilbertohasnofb** [comment] 2018-02-26 01:26
> Can we close this issue as won't fix if the models are going to be replaced?

:+1:

**Closed** 2018-02-26 01:55 UTC
Labels: 3D model, enhancement, wontfix
