### ISSUE TITLE
pontoon angle alignment with craft and ground

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p-detailed#214] opened 2015-05-27 20:02 UTC
is our CG a little off when wearing either of the floats or are our struts off just a little? i've been looking at some pics of the 172 with floats and those seem to sit much flatter and level than this craft... check this image at the wipaire site...
http://www.wipaire.com/Wipaire-Dev/piwigo/i.php?/upload/2012/06/18/20120618121559-882f7b8a-sm.jpg
it just seems like our craft is a bit more nose up when wearing the floats... i notice it all the time when i can't see the area in front of the craft in the sim... i'd like to find some photos of the craft just sitting on the water to compare with... all my flying and testing have been done with no baggage or additional weight... just the 180 pound pilot and whatever fuel is standard to start with...

**Comment by wkitty42** [comment] 2015-05-27 20:15
here's a shot from the sim... the floats and craft angles are off compared with the above referenced picture... floats are angled down and the craft nose is raised... can this be fixed easily and ready before the freeze?
![fgfs-screen-030](https://cloud.githubusercontent.com/assets/4641713/7846433/7c9a2f5c-048b-11e5-9aad-3f36b2412aea.png)

**Comment by dany93** [comment] 2015-05-27 22:02
Currently, that is a pure effect of the gear height. Geometry.
The CG cannot be off because (I think) you do not still have their weight taken into account (unless you are testing the pull request https://github.com/Juanvvc/c172p-detailed/pull/212#issue-80878085. 
The CG position in written in Fuel and payload. Check if the weight changes and if the CG moves with floats or not.
Read above your message here https://github.com/Juanvvc/c172p-detailed/pull/212#issue-80878085, it is the subject of this pull request.


If there is an off angle, it can be fixed (by the gear height). But, differently from you, I rather feel that the aircraft nose in the sim is lower than your picture.

**Comment by wkitty42** [comment] 2015-05-28 03:21
yes, i thought later, after i wrote this, that it isn't the CG... the nose gear needs to be a little longer to make the top of the pontoons level with and parallel to the ground... the front mounting struts should also be a little shorter to lower the nose... the pics i've looked at and the one i linked to earlier show a more parallel set of lines between the top of the pontoons and the bottom flat area of the craft from the rear of the door opening to the engine compartment... that instead of the parallel portion being of the tail behind the door opening and the pontoons... i'll try to prepare a pic if needed IF we really should take care of this... i noticed it some time back but have only now just gotten around to mentioning it :(  sorry for that :( :( :(

**Comment by dany93** [comment] 2015-05-28 10:26
Yes, now I understand what you mean for the levelled pontoons (should be more parallel to the ground) and the angle between the craft and the pontoons to compensate.

**Comment by wkitty42** [comment] 2015-05-28 20:57
yes, he is doing a fantastic job... i wish i had half of the ability that his little finger has...

FWIW: i also mentioned this because i thought maybe taking care of it sooner than later would be better than having to redo anything else that already may need to be handled when it is all incorporated together... but i realize now that maybe i should have said something sooner when the pontoons were first brought out...

**Comment by dany93** [comment] 2015-05-28 22:34
You may be right for the "better sooner than later". Especially because this can have an effect on the wing angle of attack at acceleration for taking off from the water, if  the pontoons floating pitch is matched to the water.
But by reading the current forum http://forum.flightgear.org/viewtopic.php?f=4&t=25157&sid=bcdc03969281f82aef38f451b4e8037c&p=244634#p244625 I wonder if there will not be important changes...

**Comment by wkitty42** [comment] 2015-05-29 00:24
exactly on the "sooner" part... yes, i've read the forum topic and i feel the same about important changes... i just hope that everything can be taken care of before the freeze... i'm kinda wondering about that, too... is that just a code freeze for the sim or for the base craft also? yes, that's a question better asked on the dev list... i guess i'm going to have to join that sooner than anticipated... i've been reading it via the web archive interface :laughing:

**Comment by dany93** [comment] 2015-05-29 09:32
I guess the freeze will contain the features which work, with maybe a few bug fixes.
IMHO, the aircraft as it is now is already worthy enough to be in a freeze. I think that in some time, a version "almost freezed" will have to be chosen, with only bug fixes to come on it.
With a branch for the development version.

**Comment by Juanvvc** [comment] 2015-05-29 12:05
I agree with a branch for v3.6 ("the freeze", with only bug fixes) and keep the master branch in development.

**Comment by wlbragg** [comment] 2015-05-30 03:12
I was never happy with the front gear on amphibious. I tried to get the to full extension but it wasn't working, so that is part of it and yes it needs to be at full extension (in other words I think it has more travel to play with without any modeling edits. To compensate and drop the nose lower after we fix the gear extension, modeling wise, it would be be relatively simple to extend the top of the back the back struts. I would really like it if someone eventually gets to this.

How come we need to make a new branch instead of just tagging a specific commit as the 3.6 release? I don't have a problem with it either way, I'm just curious why we need another branch if the GitHub system is designed to tag a point in time (commit) as a release. Unless it is because we want to remove superfluous files like blend files from the new "release" branch. Either way is OK with me, I just hope we all agree to do it SOON!

**Comment by wkitty42** [comment] 2015-06-02 16:52
i've renamed this issue to better fit what the real problem is... i don't know how to fix this so i have to leave it to others...

**Comment by andgi** [comment] 2015-06-03 07:35
This alignment has a potentially large impact on take-off performance both on water and on land since it sets the pitch range available during the take-off run.
If a reference on how floats are to be rigged on a c172p can be found it may provide an answer.

**Comment by dany93** [comment] 2015-06-03 16:46
We at least have this drawing in the POH.
http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf
Section 9, SUPPLEMENTS
FLOATPLANE, Section1, Figure 1 p.4 of 42 (**PDF p.198/357**).
After this image, the angle does not seem so bad ?
But these floats seem smaller than wlbragg's (I s.
![capture du 2015-06-03 18 34 47](https://cloud.githubusercontent.com/assets/11994061/7965681/5a9daa98-0a1f-11e5-92aa-e76023a2a200.png)

**Comment by wkitty42** [comment] 2015-06-03 19:13
@dany93 yes, there is a difference... that pic in the manual is for floats and i was looking at the amphibious on the wipaire site linked in my first post... looking at it again, it appears that the front caster wheels are lifting the front of the craft and leveling the pontoons so their top is parallel with the ground... aside from that, i was looking also at that picture for the angle between the top of the pontoons and the belly of the engine and seating area of the craft... if it is decided that this needs some adjustment, we can hold off until the next version if it will be too much before the freeze... it was just something that i saw different and thought to bring it up for discussion...

**Comment by dany93** [comment] 2015-06-03 21:40
I think that the important is, as you wrote, the angle between the top of the pontoons and the belly of the *engine and seating area* of the craft. To be good on the water, it is common to the pure floats and amphibious version.
I guess the top of the pure floats or amphibious floats is not far from parallel to the water surface. If this angle is good, the top surface must also be parallel to the ground too with the caster wheels. The same amphibious give the angle of attack of the aircraft on the ground and on the water (presuming that the angle of attack is the same for ground and water acceleration before takeoff).
As pointed by wlbragg, it is a matter of height for the front caster wheels on your FG picture..
Not easy for the 3D drawing of the floats themselves, a sufficiently accurate representation of the reality is necessary.

**Comment by wkitty42** [comment] 2015-06-03 22:03
ok... so... we hold this issue open for future visitation and evaluation or?

**Comment by dany93** [comment] 2015-06-03 22:54
The solution does not depend on me, but I would let it open.

**Comment by wkitty42** [comment] 2015-06-04 03:05
yes, i'm leaving it open for more comments from everyone else...

**Comment by wlbragg** [comment] 2015-06-04 06:22
I think we need to start with the front caster wheels and get their compression and extension adjusted to the correct specs. I really don't know how to do that.
Once that is correct then we can look at the angle of attack of the aircraft. I think the angle of attack will be a simple fix. I'm pretty sure it will only require the extension of the two back strut attachment points to get the angle how we want it.

**Comment by wkitty42** [comment] 2015-06-04 13:06
@wlbragg that's my thoughts, too... perhaps a closer look at some amphibious pontoons can help?

**Comment by dany93** [comment] 2015-06-04 17:51
>I think we need to start with the front caster wheels and get their compression and extension adjusted to the correct specs. I really don't know how to do that.

I do not understand the problem.
These gears are boguey 21 and 22.
The spring and damping coeff are in the FDM (lines 416 .....).
In the FDM, their Z-position is 0, but it seems that you set it in physics.nas
```javascript
var amphibious = func
{
	resetcontacts();
	resetalldamage();
       (......)
	setprop(gears~"unit[21]/z-position", -54);
	setprop(gears~"unit[22]/z-position", -54);
```
(Not sure this is truely set here, I don't understand well. Fix me, please....)
Why not set it by 
```
fdm/jsbsim/gear/unit[21]/z-position
fdm/jsbsim/gear/unit[22]/z-position
```
?
It can lift the front of the amphibious, after that is a matter of 3D in Blender to have it just on the ground?
With -60 the top surface of the amphibious is almost horizontal.
You will probably have to decrease the length of the front struts to get the aircraft pitch angle.
I know that it can be a true work in Blender....

But I may not have understood well....

**Comment by wkitty42** [comment] 2015-06-04 19:46
i think you have it, @dany93 ... decrease front struts or lengthen back ones... either way will adjust the angle of the craft in relation to the pontoons... the question is which one to do to have proper clearance between bottom of spinning propeller and top of pontoons... yes, i know the prop is in between them but... :wink:

**Comment by dany93** [comment] 2015-06-04 22:03
Yes and no. I rather understood that wlbragg had a problem at setting the compression and extension values for the front caster wheels in the FDM. I trust him for Blender.

**Comment by wkitty42** [comment] 2015-06-04 22:20
yes, the casters is one... fixing that should level the pontoons... then the craft itself needs to be adjusted so it isn't so nose-high (too high angle of attack?) when the pontoons come up level...

**Comment by wlbragg** [comment] 2015-06-05 05:37
"I do not understand the problem.
These gears are boguey 21 and 22.
The spring and damping coeff are in the FDM (lines 416 .....).
In the FDM, their Z-position is 0, but it seems that you set it in physics.nas"

I'm not sure I understand either. I don't set any of the gear bogey points in the FDM because we don't know for sure what gear configuration is going to be used at any point in time or at startup.

As far as the front amphibious gears not being configured correctly, I don't think it can be fixed with the z-position, I think the problem was the weight VS spring/compression settings of the parts of the gear. It compresses them too much just sitting there.

It's been awhile since I experimented with it and I have forgot exactly what my issues were with trying to adjust them. Let me take a quick look at them again tonight and play with their settings so I can refresh my memory and better explain why I couldn't get them to extend the way they should.

**Comment by wlbragg** [comment] 2015-06-05 07:02
OK, I just got through looking at this again.
The issue is the spring_coeff and damping_coeff for both the front and rear amphibious gears. They are to "soft".
They are gear "bogey" points 21-24.
If I extend some other contact points 13-16 to take the weight off of the gear you can see the peak extension that they should be able to obtain.
![extended](https://cloud.githubusercontent.com/assets/11069680/8000663/79e8c0b8-0b23-11e5-8994-3fedc4d52e0c.jpg)
I know they should be under some load but not anywhere near what they are now.

Now if I remove the extra contact points and apply all the pressure on the gear you can see the compression on the gear is too great.
![compression](https://cloud.githubusercontent.com/assets/11069680/8000727/05a765be-0b24-11e5-94ca-6e2687cf5775.jpg)

The other thing at play is the complication of watching for which type of gear and which type of surface those gear are on. It makes a difference on whether or not I need to use other contact points in addition to the gear to control wind drift or ground friction. That is why I control it all in physics.nas.

Then there are another issues at play that had to be taken into account. One of those was the gear would break just by the force applied to them while switching from one type to another. So I created a delay loop to allow settling out of the aircraft before I allowed the damage loop to be active.

Then when I added the amphibious gear, I guess because of the amount of spring_coeff and damping_coeff, I found an issue where it went bonkers when extending or retracting the gear, I had to use additional contact points to steady the aircraft while the gear traveled at which time it finished its travel I could remove the contact point.

This is all done in physics.nas and the more I added the more complicated it got to the point where I started hacking solutions instead of using clear, well thought out logic, in some cases. The amphibious gear was one of those cases.

But really I think the main issue with the amphibious gear is the spring_coeff and damping_coef settings. They need to be able to handle more weight, I think.

I used contact points 13 and 14 to take some of the pressure off of 21 and 22, that is a HACK and I am surprised it works as well as it does, but is not right.

`<
setprop(contact~"unit[13]/z-position", -55);
setprop(contact~"unit[14]/z-position", -55);
setprop(contact~"unit[15]/z-position", -22);
setprop(contact~"unit[16]/z-position", -22);
setprop(gears~"unit[21]/z-position", -54);
setprop(gears~"unit[22]/z-position", -54);
setprop(gears~"unit[23]/z-position", -48.5);
setprop(gears~"unit[24]/z-position", -48.5);
>'

**Comment by andgi** [comment] 2015-06-05 11:13
If you consider merging the hydrodynamics ( https://github.com/andgi/c172p-detailed/tree/hydrodynamics-wip ) for the coming release it might be worth looking at solutions to the floats on water/land problem from that perspective.

Yesterday I removed the float contact points 13-20 and kept the float landing gears (formerly 21-24, now 13-16 in hydrodynamics-wip). This seems to work ok on land and water, apart from that the floats float if the gear is retracted on land.. (having structure points that can be moved down to the keel for this case might be a solution).  Another missing part is detection of too large forces to trigger float damage (damage itself is partially implemented - set the damaged or broken property and the float will leak and eventually sink).

**Comment by wlbragg** [comment] 2015-06-06 02:56
"If you consider merging the hydrodynamics"
Maybe you've completed some more work on this, but the last time I tried it there were several issues with it. Unfortunately I can't remember what they were.
They may be small things that can be easily fixed but I remember having the impression that it had a ways to go.
I'll pull fresh and give it another try and report back any of my concerned.
I am very hopeful that your code can eventually replace the nasal hacks we're using now.

"Having structure points that can be moved down to the keel when on ground might be a solution"
That is exactly how I am handling floating and other undesirable things.

**Comment by andgi** [comment] 2015-06-06 14:06
If you pull now floats on ground (issue i) above) is now better handled along the lines you had before, but only when there is solid ground below the contact point. The hydrodynamics system is on unless all contacts are above solid ground.

There are things that may need some more tuning, such as: the location of the forward float contact point and the friction values - there is strong a tendency to nose over when the float contacts the runway even at moderate speed. The condition of spark particle systems and the damage detection system also need attention.

**Comment by onox** [comment] 2015-06-06 14:54
@andgi I tried your branch yesterday, but the aircraft reacted really badly when touching the water during landing or during takeoff.

**Comment by andgi** [comment] 2015-06-06 15:06
Are you sure you didn't touch down too hard? I can make acceptable landings but it is not trivial, but that is somewhat consistent with what I have read about seaplane handling.
Do we have anyone with actual seaplane experience around?

**Comment by dany93** [comment] 2015-06-06 17:27
@wlbragg 
I am trying to understand your amphibious gear issue.
Thus, pardon and don't be surprised if I write non sense.
>But really I think the main issue with the amphibious gear is the spring_coeff and damping_coef settings. They need to be able to handle more weight, I think.

In your first picture https://github.com/Juanvvc/c172p-detailed/issues/214#issuecomment-109181958 the Z-position of the wheels do not seem so bad (although not easy to evaluate when they do no touch the ground)..
In the FDM the spring coefficients (bogey, 21 - 24) seem correct with 2500 and 5400 LBS/FT (damping do not matter here).
In your second picture, the top surface of the floats is almost horizontal, the height above the ground may be close to good.
Up to there, I'd say that the compression in the FDM and Z = 60 values are not far from good.

The only issue is the viewed position of the front wheels in your 2nd picture, which means a 3D issue for me (not a FDM issue).
I feel that is an *animation which is over-amplified*. 
That is obvious if you observe from outside. Roll and accelerate enough, pull the yoke or press the brakes: the front wheel enters underground or go out instead of just following the difference in compression.
Here, that is worse because the stroke is weak, 2500 LBS/FT for these front springs is a bit hard. The nose weight is divided between the two, which makes only 8 - 9% compression on it. This spring coefficient is not an issue, but for this weak stroke you have a much too large 3D displacement.

The animation is in Models/c172p.xml, lines 5067 and 5137 (gear 21 and 22)
  ```
<!--    Retractable Gear    -->
  <animation>
    <type>rotate</type>
    <object-name>Ldamper</object-name>
    <property>gear/gear[21]/compression-norm</property>
    <factor>7</factor> <!-- initial 91.5 -->
```
 (maybe fdm/jsbsim/gear/unit[21]/**compression-feet** would be better, because if you change the spring coefficient I think the animation in feet would remain good)

Just to check if I have understood your issue well, what would you think of: (for gear 21 and 22)
FDM c172p.xml, lines 426 and 441, **spring_coef =1000** (instead of 1500 or 2500)
Models/c172p.xml **factor 7** (like my line above, instead of 91.5)
fdm/jsbsim/gear/unit[21]/**z-position = -62** (in physics.nas lines 277 -278, true?)

These animations are always very hard to adjust. Difficult to work rigorously.

But firstly, am I beside your issue or not?

**Comment by wlbragg** [comment] 2015-06-07 03:46
"I feel that is an animation which is over-amplified."
You are probably right. The animation was not a 1 to 1 copy from the dhc2 because I resized the landing gear and the tires. So that make sense that it is more likely animation which is over-amplified VS spring.
Feel free to work on it and see if you can improve on it, that whole area of development is out of my wheel house.

**Comment by wlbragg** [comment] 2015-06-08 21:40
andgi, has a fix and we should be able to put this to rest shortly after he gets the pull request sent..

**Comment by andgi** [comment] 2015-06-09 08:07
@wlbragg I'm not completely happy with how the aircraft floats when idle with the hydrodynamics system - the H(YDRO)RP is currently offset forward compared to what the buoyancy data was generated for to compensate which is clearly a hack - but OTOH the resulting reactions are okish. It is one area for further refinement, but most likely not before the 3.6 freeze.

**Comment by wlbragg** [comment] 2015-06-09 15:32
The gear PR has been merged, Now we need to verify we are OK with the AOA and then we can close this issue.

**Comment by dany93** [comment] 2015-06-09 16:54
Not really the AoA, but the pitch angle (stopped):
with the default gear: 2.7°
with the amphibious: 4.1°
Not sure this is very important, we set the AoA as soon as taken off. The higher AoA can lengthen a bit the roll, but anyway the amphibious is not the better choice if we look for performance.
On the water it remains to be seen (I know nothing....). But also, the pitch angle, hence the AoA during acceleration, is set by acting on the elevator. See http://www.seaplanes.org/mambo/UserFiles/File/AC61-21A.pdf (link by tigert).

**Comment by wlbragg** [comment] 2015-06-09 18:33
"Not really the AoA, but the pitch angle "
Sorry, poor choice of words.

So do you think the pitch need to be adjusted?

**Comment by tigert** [comment] 2015-06-09 19:40
To me it looks like the Flightgear floats and fuselage have too big angle. 

http://www.vesilentokerho.info/wp-content/gallery/kellukeasennus/oh-ctl_05-07-2013-129.jpg
http://www.vesilentokerho.info/wp-content/gallery/kellukeasennus/20130625_181541.jpg

There is an angle but I think in the simulated version it is a bit too big.

**Comment by dany93** [comment] 2015-06-09 22:37
It was not for your choice of words, pitch angle and AoA have the same value when the aircraft accelerates on the runway. Merely, the pitch angle can be obtained even when the aircraft is stopped.

Yes, I also feel that this angle is a bit too high, from tigert's second picture and this scheme in my message https://github.com/Juanvvc/c172p-detailed/issues/214#issuecomment-108519431.
Difficult to evaluate by the eye, but a value could be the one with the default gear (2.7° instead of 4.1°, check in the simulator). Which gives a 1.4° difference (easy to measure).
By trying to measure (more difficult) the angle between the upper surface of the amphibious and the lower part rear of the aircraft, I evaluate this angle at about 2° in FG, 4.5° on the scheme.
Unless you can superpose the scheme in Blender.
I do not know which is the better. The pitch angle is easy to get in FG, and taking the default gear's one as a reference value seems sensible.

But I know this small difference gives a true work in Blender. This was why I wrote "Not sure this is very important" (in practice)  because we can act on this angle with the elevator.. This is rather to  look like reality. 
Also, don't be surprised, this change will lead to readjust the Z-values for the gears, because the reference axis from the ground is the aircraft. This should not be difficult.

**Comment by wlbragg** [comment] 2015-06-09 22:49
"But I know this small difference gives a true work in Blender."
I was just looking at this in blender and xml, No real easy way I can find to fix this unless we can change pitch of c172p.ac on the fly when pontoon is selected for gear. That would be the easiest fix, if even possible.
I superimposed a RL picture of a float c172p with a screenshot of ours and the difference was not great, but it was there. Also the size (length) of out floats are longer than RL. But so was the shape of the fuselage different in RL VS ours.

**Comment by onox** [comment] 2015-07-08 07:03
@wlbragg @dany93 @andgi Can this be fixed this week or should we move it to 3.8 release milestone?

**Comment by wlbragg** [comment] 2015-07-08 07:36
I did this in about 2 minutes. What I don't know is if it requires any other changes like contact points or something else.
All this required was select everything in Models\Effects\pontoonc172p-pontoon.ac and rotate 3 degrees, edit Models/c172p.xml (line 6) and subtract 3 degrees from pitch. 
We would also have to do the same in c172p-pontoon-damage.ac.
Plus we would have to account for this change in all other configurations and put the 3 degrees back in on the change over.
Probably needs to wait for 3.8 to be safe.
![fgfs-screen-004](https://cloud.githubusercontent.com/assets/11069680/8565230/3df6187a-2519-11e5-9ea3-7a45f933ffc5.gif)

**Comment by onox** [comment] 2015-07-08 07:41
Wouldn't it be better to adjust the pontoon part instead of the fuselage and everything else?

**Comment by andgi** [comment] 2015-07-08 09:51
It certainly needs changes in the FDM: moving all float gears and contact points and adjusting the orientation and position used by the hydrodynamics system. The tables for buoyancy were computed based on the position and orientation of the floats in the poonton model file so the change can be accounted for by the offset in the hydrodynamic pitch property - at least if the floats were rotated around the VRP/centre of the top level model coordinate system.

**Comment by dany93** [comment] 2015-07-08 10:36
I am currently looking at this and it is not at all simple.

Setting the 3D attitudes is just for the 3D view.
Setting the FDM, attitude, Z-positions are in the FDM **c172p.xml** and in **physics.nas** for the buoyancy on water, wheels on ground and **c172p-hydrodynamics.xml** for the planing attitude.

**Do not confound the 3D representation, which is pure illusion, and the FDM attitude.**

I currently read (/orientation/pitch-deg)

default wheels; 2.65° (I would take this as a Reference?)
26": 0.53°
63": -1.70°

Amphibious on the ground (wheels): 4.1° (+1.45°)
Amphibious on water, engine and *aircraft stopped on water*: 4.4° (+1.75°)
Floats on water, engine and *aircraft stopped on water*: 4.7° (+2.05°).
==> Only +1.45° to +2.05° compared with default wheels. Not so far (less than the 3°)
I ignore what the FDM pitch-deg values to aim are for floats on water. Small differences can be made good with the elevator, if the float reactions are not too hard.

The (most important) attitude to takeoff on water is driven by the hydrodynamics. More difficult to measure.

I respond because you are on it and I do not want to make you waiting, but at this time, I cannot say more.

**Comment by wlbragg** [comment] 2015-07-08 12:47
dany93 right, this is just the visual representation which is relatively minor but not without some issues. The floating of the wheels in the second image was because I guessed (did this by sight) at the pitch and it wasn't done precisely.

>Wouldn't it be better to adjust the pontoon part instead of the fuselage and everything else?

That is what I did, but the way they are attached in the physical world of FG code, when you pitch just the pontoons in the model and run the sim then the front of the pontoons float up the amount of applied pitch. You have to counter that degree of pitch in the c172p.xml file to compensate and bring it back down to level.

It appears to be the extent of FDM adjustments that may be the show stopper.

**Comment by dany93** [comment] 2015-07-08 15:33
>Wouldn't it be better to adjust the pontoon part instead of the fuselage and everything else?

Here is *my current* understanding:

For the flying behavior, the reference axis are obviously those of the FDM.
But the 3D representation follow those FDM axis when they move relatively to the ground.
Offsets are almost always applied to compensate for the differences between 3D and FDM axis, but as we only see the 3D representation, applying wrong offsets to obtain an illusion is easy. 

In the FDM reference axis, the important points are the propeller location and the wheel contacts location, which are given in the fdm file. These wheel contacts give the FDM axis position relatively to the ground or water (and the 3D representation, if the offsets are good).
Ideally, the X axis in the FDM should be parallel to its equivalent in the 3D representation, but this is not explicitly defined.

Which means that the fuselage is the reference. **It is good now with default wheels, do not offset it**. Its position and orientation (height from the ground or water, attitude) is given by the Z values for wheels in the FDM coordinates (c172p.xml for default wheels, physics nas for bush and amphibious wheels).

The aim was to decrease the angle of the floats representation relatively to the FDM axis. I don't know which is the best way, but you have done it.
But after that, did you change the fuselage position relatively to the ground with the FDM (physics.nas, c172p-hydrodynamics.xml) or by a 3D offset angle?
If you have done it by a 3D offset angle, all that you have done is only changing the *representation* of the floats and fuselage. Changing their angle relatively to the FDM axis.
But you have changed nothing in the FDM, the angles (AoA, pitch) are the same. If they were wrong they are still wrong.
Moreover, I the fuselage position with the default wheels will be wrong.

To readjust after the viewed float angle change relatively to the fuselage (= FDM axis), you have to:
- On the ground, to change the Z values, at least decrease Z for the front gears (physics.nas if I remember well),
- On the water, *at least* decrease or cancel the pitch value offset (currently = -3.0) in c172p-hydrodynamics.xml, line 339.
```
  <fcs_function name="hydro/float/pitch-deg">
   <description>
    The float pitch with the trim change due to waves and
    the displacement wave applied.
   </description>
   <function>
    <sum>
     <value>-3.0</value> <!-- The float model is 3 deg offset in pitch. -->
```

From what I understand of the c172p-hydrodynamics.xml, this should make the FDM **AND the 3D model** to pitch down by 3°. The floats front will go down with the fuselage and the FDM front axis.


Applying an offset on the 3D model is only for the eyes, but the FDM will remain unchanged.
If you change nothing in the FDM (Z for the amphibious wheels in physics.nas, offset angle in c172p-hydrodynamics.xml, the FDM will still be wrong. 

Rather than applying an offset angle on the 3D fuselage representation, I think that the changes must be done in the FDM (Z in physics.nas and float pitch in c172p-hydrodynamics.xml). By changing the contacts with ground or water, the FDM axis should pitch down by 3 deg and the 3D representation (fuselage  + floats) should follow. Like this, the pitch angle and the AoA in the FDM will be changed. 

Very difficult to explain, I'm never satisfied. And I may have done mistakes....

@andgi help!!!

**Comment by andgi** [comment] 2015-07-08 16:54
If the floats have been rotated up around the right centre of rotation (i.e. the VRP) then reducing the 3 deg offset with the same amount should be ok. Note also that I offset the Hydro RP in the hydrodynamics file forward by 10 inches (guessed) just to get a "decent" idle attitude, so even the old visual representation isn't exactly in tune with the FDM buoyancy.

The float contact points (for land reactions) OTOH have been placed fairly precisely from the 3d model with the transformation to FDM space considered (see `bushkit.xml` and `c172p.xml`). These will also need to be moved.

It is unfortunate that this model has such a mess of coordinate frames, thanks to whoever introduced the 3 deg rotational offset (and a bit less so the z-offset) between the 3d model and the FDM frames.

**Comment by dany93** [comment] 2015-07-08 17:26
Thanks @andgi for having responded so quickly.
>reducing the 3 deg offset with the same amount 

I guess you mean in c172p-hydrodynamics.xml?

**Comment by andgi** [comment] 2015-07-08 18:57
@dany93 Yes. `c172p-hydrodynamics.xml`.

**Comment by wlbragg** [comment] 2015-07-09 17:54
All I did was the "visual", the appearance of being correct, which included changing the fuselage pitch angle.

I was just testing to see what was required on that end of this.

Even though that part of it is easy enough, it still may require slight translation axis changes on the x and z maybe even y (y less likely). But that should be only to the floats structure and should be so slight that is really shouldn't cause any trouble FDM side. 
It may also require physical adjustments to the mesh in the pontoon model to get the attachment points to line up the way we want. I know I got lucky that they just so happened to line up fairly well, but that may also be why the size of the pontoons are what they are (because the struts fit best that way). I don't remember my logic for sizing it, but I can tell you now I wish I had paid more attention to reality at the time for size and pitch, they should be a bit smaller also.

Below is a gif visual of the current "visual" pitch changes. I guess the FDM is handling these pitch changes only between wheels and floats, but not between float geared and not geared or between bush kit wheel changes?
https://copy.com/DX7ZLD4elvC77WNk

**Comment by dany93** [comment] 2015-07-09 22:46
Impossible to say from this if the visual appearance matches the FDM attitudes.

You have been led to change the pitch angle of the fuselage (relatively to the FDM axis) because you didn't change the FDM contacts (with water or ground). In a perfect world, the 3° pitch up of the pontoons should have been compensated by a 3° pitch down of the entire aircraft (fuselage  + pontoons) *by the FDM*. The FDM change being (I think) the 3° offset cancellation in c172p-hydrodynamics.xml, and a decrease of the Z value for the amphibious front wheels. Both have the same effect, the first on water, the second on the ground.

The effect of the bush wheels is questionable, but this has nothing to do with the float issue.

The effect of the floats / amphibious on the FDM is in [these pitch angles](https://github.com/Juanvvc/c172p-detailed/issues/214#issuecomment-119536658). It is not large, at worst about 2°. As long as the float interface with water (float angle) and the amphibious wheel is not changed, the effect on the FDM is obviously unchanged from these numbers.
If changes had to be done on the FDM part (e.g. pontoon angles in c172p-hydrodynamics.xml), I notice that the current effect of the pontoons in the FDM is +1.45° to +2.05°, less than the 3° of the representation.
So, all of this is not rigorous in its principles, but the error is limited to about 2° for the FDM.

I totally ignore what the reality is.

**Comment by wlbragg** [comment] 2018-04-04 23:46
I think the current PR covers this topic and will close it out.

**Closed** 2018-04-22 00:08 UTC
Labels: FDM, enhancement
