### ISSUE TITLE
FDM: fix right turning tendency

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1113] opened 2018-05-23 10:24 UTC
Now you will feel the plane has a little bit RIGHT turning tendency, yes RIGHT direction not left! Very little left rudder could compensate it easily.

As #1112 mentioned.

**Comment by algefaen** [comment] 2018-05-24 09:32
For the record, if you're gliding (turn off the engine), you should see a slight right turn, since the airplane is rigged to counter propwash/torque/etc.. Please do these "is the plane flying straight" tweaks at cruise settings (2300 RPM might be a good setting for this).

**Comment by onox** [comment] 2018-05-25 06:49
@dany93 This issue should fix the aileron trim thingy you forgot to put back in the FDM?

**Comment by wlbragg** [comment] 2018-05-25 07:17
@onox, yes we can use this as the catalyst if @dany93 wants to open a PR and refference this issue. It was already stated that the issue is indeed "the thingy he forgot to put back into the FDM!" 😄 @gilbertohasnofb suggested @dany93 open an issue and PR to correct it but it looks like @tonghuix beat everyone to it.

**Comment by wlbragg** [comment] 2018-05-25 07:33
@tonghuix are you indicating you want to close this issue and let @dany93 fix it by correcting his omission?
If so I am saying almost the same thing as his correcting his mistake will automatically close this issue if we attach the PR to this issue.

**Comment by tonghuix** [comment] 2018-05-25 07:42
@wlbragg agree, but I hope when merging his PR let this issue automatically close.

**Comment by dany93** [comment] 2018-05-25 09:28
I will open an issue and a PR next as @gilbertohasnofb asked, please just let me some time.
It will include the aileron trim correction (which is a small detail), and, more importantly, propose a start code for canceling or decreasing the spiraling propwash.

**Comment by gilbertohasnofb** [comment] 2018-05-25 09:40
@dany93 No rush, Dany, that sounds great. Take your time with this issue.

**Closed** 2018-05-25 21:02 UTC
Labels: FDM, bug
