### ISSUE TITLE
State support in the C172P

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#856] opened 2016-11-08 22:35 UTC
State support for our plane is being discussed in the mailing list: https://sourceforge.net/p/flightgear/mailman/message/35478527/

@onox @wlbragg or whomever is comfortable with the subject, could you please check this thread out?

**Comment by onox** [comment] 2016-11-09 21:15
I think we need to be able to set properties at the very least and maybe also have Nasal scripting. Furthermore, we need to be able to specify the (internal) state of the JSBSim FDM and its systems, including intermediate properties (used as input for other JSBSim components in a system).

Basically what we want is to be able to take a snapshot of all the properties that we're interested in, Nasal state (listeners, timers, etc.), state of instruments, and in particular JSBSim state (stuff that is not exposed to the property tree, like internal variables of certain JSBSim components). And then to be able to let FG resume from such a snapshot.

If we cannot save/resume internal state of JSBSim systems, then it would be more difficult to properly initialize certain systems. For example, the heat system needs time to adjust to adjust certain values.

What do you guys think?

**Comment by wlbragg** [comment] 2016-11-09 21:24
Yes, agreed.

See https://sourceforge.net/p/flightgear/mailman/message/35481658/ for the starting point.

I am not aware of or familiar with "modify the example -state.xml files". I just looked at the State folder, this is the first I have seen of it.

**Comment by wkitty42** [comment] 2016-11-10 02:09
On 11/09/2016 04:15 PM, onox wrote:
> I think we need to be able to set properties at the very least and maybe also
> have Nasal scripting. Furthermore, we need to be able to specify the (internal)
> state of the JSBSim FDM and its systems, including intermediate properties (used
> as input for other JSBSim components in a system).
>
> Basically what we want is to be able to take a snapshot of all the properties
> that we're interested in, Nasal state (listeners, timers, etc.), state of
> instruments, and in particular JSBSim state (stuff that is not exposed to the
> property tree, like internal variables of certain JSBSim components). And then
> to be able to let FG resume from such a snapshot.
>
> If we cannot save/resume internal state of JSBSim systems, then it would be more
> difficult to properly initialize certain systems. For example, the heat system
> needs time to adjust to adjust certain values.
>
> What do you guys think?

i think this is very close to what is sought... the goal being to regain startup 
options like "in air at 10 miles on final"... in this case the craft should be 
set to the normal properties that one would have when flying in at that point in 
time...

the complication with this craft comes from the two different engines and 
selecting which one is active in this scenario... add to that the various 
additional complications stemming from the different landing gear possibilities...

we need some way for those choosing this scenario to also select which landing 
gear and engine they desire... there's quite the selection tree to manage based 
on the options the craft offers...

**Comment by zakalawe** [comment] 2016-11-17 20:21
Following up one Denk's comments. Exposing JSBsim internal state, or Nasal timers, is not possible, it's much too complicated. What we can do is run a 'trimming phase' (indeed, JSBsim already does) so things like heaters can stabilise. How much complexity is needed for that, is precisely the question we need to answer.

For example I could run the system for 5 (simulated) seconds (so 600 time steps, at the 120Hz core simulation rate), but with the FDM position and velocities locked out. I imagine this would be fine for the instrumentation code to settle. (We would of course set some flag like /sim/trimming while doing this).

If this sounds workable, great. If this is /still/ insufficient, then we have a fundamental obstacle but I need to understand what it is so we can start making whatever underlying C++ changes might be needed. Again I think with the amount and age of items in FlightGear's C++ (instruments, Nasal, FDMs) doing a 'perfect' save and restore isn't possible.

**Comment by onox** [comment] 2016-11-17 23:40
Is the number of time steps / seconds configurable? And per system or globally? A trimming phase does indeed sound workable.

**Comment by zakalawe** [comment] 2016-11-18 15:31
That's all to be decided! I will raise the proposal on the mailing list, but I need to check with the FDM folks, since they already have a trimming phase internally. My guess is we want to run a 'system trim' immediately after the FDM trim is complete (so basic motion properties are stable, airpseed, etc).

I will also make some experiments how fast we can run this. Current idea would be to run a simulated second; with rendering disabled I expect we could run this pretty quickly (a few seconds at most).

**Comment by wlbragg** [comment] 2016-12-01 20:54
Now that state support aircraft side is being improved, there needs to be a dev discussion on whether a GUI launcher state choice can be supported. It might be easier for the aircraft to set a state choice in the launcher, or more accurately, the launcher detecting a state choice in the aircraft parameters or code. With robust state support aircraft side, a simple hook to a predefined method of setting a GUI state choice in the launcher would make the most sense and give the greatest flexibility.

**Comment by wlbragg** [comment] 2016-12-01 21:03
For example, aircraft side a simple xml block could set the available state choices for this aircraft in the GUI launcher.

For example,
~~~xml
<states>
 <approach>Final Approach</approach>
 <bushwheels>Bush Wheel Configuration</bushwheels>
  <180engine>180 hp Engine</180engine>
</states>
~~~
It could be limitless, to be decided by the aircraft developer/s.

**Comment by zakalawe** [comment] 2016-12-01 22:04
I would prefer it /not/ be limitless, to be honest. The goal of this is to improve the end-user experience. Exposing different *configurations* such as a 180HP engine or Bush wheels is a job for the variant system, with multiple -set.xml files. The state system is for different states of the same aircraft, which the launcher can auto-select based on the user's desired start position.

**Comment by wlbragg** [comment] 2016-12-02 04:26
>I would prefer it /not/ be limitless
>The state system is for different states of the same aircraft, which the launcher can auto-select based on the user's desired start position.

@zakalawe understood, my exuberance got the best of me.

**Comment by wkitty42** [comment] 2016-12-02 23:01
@zakalawe since this craft has multiple configurations but only one -set file how can one select a variant configuration in the --launcher for use with the different states?
are you saying that this craft has to ""revert back"" to multiple -set files for the different configurations for use with the states?
the guys did an awful lot of work to combine and get rid of multiple -set files to make it easier to maintain so that one -set wasn't updated and others forgotten... another high goal was to allow one to change the craft's configuration without having to exit the sim and restart it via a new -set file...

**Comment by zakalawe** [comment] 2016-12-02 23:41
Well unfortunately combing into a single set file was the wrong thing to do - multiple set files are the supported and correct way to handle configurations. It's entirely normal and recommended to share most of the -set.xml between variants by include a 'common' XML file, most aircraft which have variants do this. No duplication is needed.

Changing configuration at runtime is handled in the same way as aircraft switching at runtime - by the reset system. Since configurations might potentially use a different FDM or instruments, a full reset is the only safe option here I think.

I'm sorry if time was spent on doing something different but making an ad-hoc solution specific to the C172P is not great, since other aircraft may copy the same idea and we'll end up with a mess.

**Comment by wlbragg** [comment] 2016-12-04 05:50
@zakalawe,  looking at the examples in state I need some clarification to proceed.
In approach-overlay.xml you have

~~~xml
<name type="string" n="0">approach</name>
<name type="string" n="1">circuit</name>
~~~
yet in cruise-overlay.xml you have
~~~xml
<name type="string" n="0">cruise</name>
<name type="string" n="1">climb</name>
~~~
Were these two independent examples that you happed to throw in there for reference? I don't get the correlation between the two unless it is really supposed to be
~~~xml
<name type="string" n="0">approach</name>
<name type="string" n="1">circuit</name>
<name type="string" n="2">cruise</name>
<name type="string" n="3">climb</name>
~~~
in each configuration file?

In the <overlay> section I assume all the examples are supposed to represent properties in the FDM that need to be initialized for that state.

ie:
~~~xml
<overlay>
        <foo type="int">42</foo>
    </overlay>
~~~
and
~~~xml
<overlay>
        <wibble type="bool">true</wibble>
        <sim>
            <dimensions>
                <radius-m type="double">10</radius-m>
            </dimensions>
        </sim>
    </overlay>
~~~
all represent various existing properties we need to set for each state?
Where you are using
foo
wibbly
/sim/dimensions/radius-m 
all as examples of properties that might need to be initialized for that startup state?

I started adding some of the properties needed to startup in air on approach. My first goal is  to see that the code in the state files is being read and executed.

Is there any documentation on how to code and activate this?

I assumed --state=0 in the launcher or cmdline would activate the first named state?

**Comment by zakalawe** [comment] 2016-12-04 21:28
It's two independent examples, both with two names.

And the overlay represents any properties (not just FDM) you want to customise in the state.

--state=climb will activate the state named 'climb' 

Note from some discussions with Torsten R and others, I am expecting that simply setting properties will not be sufficient for in-air starts. What I am planning to do, is add a 'simulator-trim' phase that happens right after the FDM-trim, where we advance through (at a guess) one minute of simulated time as fast as possible in real time. (Hopefully this will take a few seconds if rendeirng is disabled).

This will be done with a flag property set, /sim/trimming=true for example (again property name not decided yet!), similar to /sim/freeze/

The idea is that will give lots of filters / interpolators / Nasal code time to stabilise on the values. The FDM will *not* be updated so the FDM values (start position, velocity, altitude) will be the same.

I am hoping this will make in-air starts easier for aircraft developers. I can code this up 'quite soon', what I don't know is how far you can get using the existing code, before you hit a Nasal thing that really needs some time passing to stabilise.

**Comment by wlbragg** [comment] 2016-12-05 00:42
>--state=climb will activate the state named 'climb'

OK, I tried that first but it didn't appear to do anything. All I was trying to do was set flaps or anything simple so I could confirm I was activating the state code.

So I should be able to do something like below
~~~xml
<?xml version="1.0"?>

<PropertyList>
    <name type="string" n="0">approach</name>
    <name type="string" n="1">cruise</name>
    <overlay>
	<consumables>
		<fuel>
			<tank n="0">
				<selected type="bool">true</selected>
			</tank>
		</fuel>
	</consumables>
	<controls>
		<flight>
			<elevator-trim type="double">0.0</elevator-trim>
			<flaps type="double">2.0</flaps>
		</flight>
		<switches>
			<magnetos type="int">3</magnetos>
			<master-bat type="int">1</master-bat>
			<master-alt type="int">1</master-alt>
			<master-avionics type="int">1</master-avionics>
			<starter type="int">1</starter>
		</switches>
		<engines>
		    <engine n="0">
			<primer type="double">3</primer>
		    </engine>
		    <current-engine>
			<throttle type="double">0.2</throttle>
			<mixture type="double">0.95</mixture>
		    </current-engine>
		    <active-engine n="0">
			<oil-level type="double">7.0</oil-level>
			<carb_ice type="double">0.0</carb_ice>
			<auto-start type="int">1</auto-start>
		    </active-engine>
		</engines>
	</controls>
    </overlay>
</PropertyList>
~~~
Initialize it like this
--state=approach
and I should start up with the properties listed in the overlay set to those values accordingly?

**Comment by zakalawe** [comment] 2016-12-05 09:37
Correct, that should work.

**Comment by wlbragg** [comment] 2016-12-06 18:31
@zakalawe 
How does this work with saved aircraft data( /sim/aircraft-data) or does it?
Does this system set the saved state properties prior to /sim/signals/fdm-initialized being true or exactly when does it set the var in the overlay?

I have bypassed any of our nasal code (initialized on /sim/signals/fdm-initialized) affecting any of the saved state parameters I set up, yet I don't see any of the the saved state overlay variables changing?

**Comment by wlbragg** [comment] 2016-12-06 18:34
For what it is worth, if I set --state=0 I do get a warning that there is no stage=0 and when I call it correctly (--state=approach) I don't get any feedback so I think I am hitting the switch.

**Comment by zakalawe** [comment] 2016-12-06 18:40
It doesn't (yet!) do anything special with /sim/aircraft-data, which is not a part of the code I've ever touched. The overlay (state) properties are set 'really early', before the FDM is inited, so the rest of the code should simply see it as a differet -set.xml.

All this is modulo any bugs that might exist of course!

What might be needed is to make /sim/aircraft-data aware of states, in case particular data variables do not make sense. But again I'm not really familiar with how that feature is supposed to function - can you give me a quick summary?

**Comment by wlbragg** [comment] 2016-12-06 19:09
That is my issue, I have bypassed /sim/aircraft-data from loading and changing any variable.

We save any parameters we want to load at fdminit by pointing to them in the -set file in the xml branch aircraft-data.
~~~xml
<!-- Save some properties when the simulator is shut down -->
        <aircraft-data>
            <path>/sim/rendering/shadow-volume</path>
            <path>/sim/model/occupants</path>
            <path>/sim/model/c172p/securing/allow-securing-aircraft</path>
            <path>/sim/model/c172p/cockpit/control-lock-placed</path>
            <path>/sim/model/c172p/securing/pitot-cover-visible</path>
            <path>/sim/model/c172p/securing/chock</path>
            <path>/sim/model/c172p/securing/tiedownL-visible</path>
            <path>/sim/model/c172p/securing/tiedownR-visible</path>
            <path>/sim/model/c172p/securing/tiedownT-visible</path>
            <path>/sim/model/c172p/brake-parking</path>
            <path>/sim/model/c172p/enable-fog-frost</path>
            <path>/sim/model/c172p/garmin196-visible</path>
            <path>/engines/active-engine/carb_icing_allowed</path>
            <path>/engines/active-engine/oil_consumption_allowed</path>
            <path>/engines/active-engine/oil-level</path>
            <path>/fdm/jsbsim/settings/damage</path>
            <path>/fdm/jsbsim/bushkit</path>
            <path>/controls/engines/active-engine</path>
            <path>/environment/aircraft-effects/cabin-heat-set</path>
            <path>/environment/aircraft-effects/cabin-air-set</path>
            <path>/controls/climate-control/overhead-vent-front-left</path>
            <path>/controls/climate-control/overhead-vent-front-right</path>
            <path>/fdm/jsbsim/running</path>
            <path>/consumables/fuel/save-fuel-state</path>
            <path>/consumables/fuel/contamination_allowed</path>
            <path>/instrumentation/save-switches-state</path>
            <path>/consumables/fuel/tank[0]/level-gal_us</path>
            <path>/consumables/fuel/tank[1]/level-gal_us</path>
            <path>/systems/electrical/save-battery-charge</path>
            <path>/systems/electrical/battery-charge-percent</path>            
            <path>/sim/model/c172p/save-state</path>
            <path>/engines/active-engine/complex-engine-procedures</path>
            <path>/sim/model/immat</path>
        </aircraft-data>
~~~
We can then load them after fdminit
~~~xml
aircraft.data.load();
~~~
We can catch that and load it when we choose to, so that in not a problem.

We also have a feature to allow a whole slew of saved switch data, but it looks like it is using a built in feature of FlightGear as we actually use the /instrumentation/save-switches-state flag to reset all those values if it is set to false. Meaning go ahead and overwrite those switch states with our default startup state if /instrumentation/save-switches-state is false. Otherwise load the last state of the aircraft, where or how that date is saved, i don't know

@onox or @gilbertohasnofb needs to shed some light on this as I wasn't paying attention to its implementation at the time. But from what I see these switch values are being saved automagically and be simply override them when we choose to.

**Comment by wlbragg** [comment] 2016-12-14 17:48
After working into this a but farther, I am still unclear about a few things, but I do have a startup condition that starts the aircraft running, with flaps at 1, x-miles out on approach, that when un-paused will almost be on a stable approach. But I doubt that what all I did is the intended method to use.
1) The load() command we use in c172p.nas appears to be executed by default somewhere in the init phase of FlightGear loading the aircraft. In other words, it loads the data in .fgfs/aircraft-data/c172p.xml by default, load() in c172p.nas is not needed to load that data.
2) aircraft-data in -set.xml is really only needed for properties not automatically found in .fgfs/aircraft-data/c172p.xml.
3) The only way I can get the data that has been added in a state overlay to be available to the fdm is by explicitly loading it in c172p.nas. It appears that load() is executed after state overlay thus why I have to change these properties after load() (commenting out the load() call in c172p.nas does not keep it from happening early on in the init of the aircraft but still after the state overlay load phase).

State approach overlay
~~~xml
<?xml version="1.0"?>
<PropertyList>
    <name type="string" n="0">approach</name>
    <overlay>
	<fdm>
		<jsbsim>
			<running type="bool">0</running>
		</jsbsim>
	</fdm>
	<consumables>
		<fuel>
			<tank n="0">
				<selected type="bool">true</selected>
			</tank>
			<tank n="1">
				<selected type="bool">true</selected>
			</tank>
		</fuel>
	</consumables>
	<engines>
		 <active-engine>
			<running type="bool">0</running>
			<auto-start type="bool">1</auto-start>
			<cranking type="bool">1</cranking>
		 </active-engine>
	</engines>
	<controls>
		<flight>
			<flaps type="double">1</flaps>
		</flight>
		<switches>
			<magnetos type="int">3</magnetos>
			<master-bat type="bool">1</master-bat>
			<master-alt type="bool">1</master-alt>
			<master-avionics type="bool">1</master-avionics>
			<starter type="bool">1</starter>
		</switches>
		<engines>
		    <engine n="0">
			<primer type="double">3</primer>
			<primer-lever type="bool">0</primer-lever>
		    </engine>
		    <current-engine>
			<throttle type="double">0.2</throttle>
			<mixture type="double">0.95</mixture>
		    </current-engine>
		    <active-engine>
			<oil-level type="double">7.0</oil-level>
			<carb_ice type="double">0.0</carb_ice>
		    </active-engine>
		    <active-engine type="int">0</active-engine>
		</engines>
	</controls>
    </overlay>
</PropertyList>
~~~
add to c172p.nas directly after load()
~~~xml
#setprop("/controls/engines/active-engine", getprop("/sim/state/overlay/controls/engines/active-engine"));
	setprop("/controls/engines/active-engine", 0);
	setprop("/fdm/jsbsim/running", getprop("/sim/state/overlay/fdm/jsbsim/running"));
	setprop("/consumables/fuel/tank/selected", getprop("/sim/state/overlay/consumables/fuel/tank/selected"));
	setprop("/controls/flight/flaps", getprop("/sim/state/overlay/controls/flight/flaps"));
	setprop("/controls/switches/magnetos", getprop("/sim/state/overlay/controls/switches/magnetos"));
	setprop("/controls/switches/master-bat", getprop("/sim/state/overlay/controls/switches/master-bat"));
	setprop("/controls/switches/master-alt", getprop("/sim/state/overlay/controls/switches/master-alt"));
	setprop("/controls/switches/master-avionics", getprop("/sim/state/overlay/controls/switches/master-avionics"));
	setprop("/controls/switches/starter", getprop("/sim/state/overlay/controls/switches/starter"));
	setprop("/controls/engines/engine/primer", getprop("/sim/state/overlay/controls/engines/engine/primer"));
	setprop("/controls/engines/engine/primer-lever", getprop("/sim/state/overlay/controls/engines/engine/primer-lever"));
	setprop("/controls/engines/current-engine/throttle", getprop("/sim/state/overlay/controls/engines/current-engine/throttle"));
	setprop("/controls/engines/current-engine/mixture", getprop("/sim/state/overlay/controls/engines/current-engine/mixture"));
	setprop("/controls/engines/active-engine/oil-level", getprop("/sim/state/overlay/controls/engines/active-engine/oil-level"));
	setprop("/controls/engines/active-engine/carb_ice", getprop("/sim/state/overlay/controls/engines/active-engine/carb_ice"));
	setprop("/engines/active-engine/auto-start", getprop("/sim/state/overlay/engines/active-engine/auto-start"));
	setprop("/engines/active-engine/running", getprop("/sim/state/overlay/engines/active-engine/running"));
	setprop("/engines/active-engine/cranking", getprop("/sim/state/overlay/engines/active-engine/cranking"));
~~~
4) By loading a sim preset parameter /sim/presets/airspeed-kt using the command line flag —vc=100 in combination with the above and setting the standard startup flag on the launcher to "On final approach at distance of" x-miles and setting the state using the command line flag of --state=approach, I achieve the aircraft running with enough forward speed to continue on glide before the nose drops out after you un-pause the aircraft (paused is the default state when using the launcher startup flag "On final approach at distance of").
In case anyone wants to test this, I'll go ahead and make a clean branch momentarily.
5) There is a parsing issue in the c++ code when trying to parse a param name that matches a path name. 
ie: the following doesn't work, it doesn't see the property active-engine = 0.
~~~xml
<controls>
		<engines>
		    <active-engine>
			<oil-level type="double">7.0</oil-level>
			<carb_ice type="double">0.0</carb_ice>
		    </active-engine>
		    <active-engine type="int">0</active-engine>
		</engines>
	</controls>
~~~

**Comment by wlbragg** [comment] 2016-12-14 18:12
Pushed to state-overlay-test.
Use
--vc=100
--state=approach
in launcher or command line.

**Comment by onox** [comment] 2016-12-14 20:37
What would make `/controls/engines/active-engine` a path?

**Comment by wlbragg** [comment] 2016-12-14 21:07
It has the same name as a path in the tree, I guess? I think it is a something that wasn't accounted for in the c++ code when parsing the /sim/state/overlay tree
~~~xml
<active-engine></active-engine>
~~~

**Comment by wlbragg** [comment] 2016-12-15 01:26
Now I am not so sure where the fault lies in the way active-engine is looked at.
In the property tree it looks like the following
~~~xml
active-engine/
active-engine[1]
~~~
So it is picking up the stand alone parameter active-engine=value (int) as the second entry in the active-engine array,
ie: 
active-engine[0] = path
active-engine[1] = value

Where as we really want active-engine[1] to be active-engine[0] or not part of an array at all.
I'm am surprised the property active-engine=value is working at all.

**Comment by zakalawe** [comment] 2016-12-15 08:42
Wlbragg, thanks for your work on this. I would suggest you take a pause now, because I suspect that once I fix / understand the core aircraft-data issue, we will be able to dispense with the your manual overlay work-around in c172.nas, and I don't want you to waste effort.

**Comment by onox** [comment] 2016-12-15 11:30
> Now I am not so sure where the fault lies in the way active-engine is looked at.
In the property tree it looks like the following
> ~~~xml
> active-engine/
> active-engine[1]
> ~~~

If I am in the `master` branch and open the property browser, then `/controls/engines/active-engine` is a an int. And there is no `active-engine[1]`. So you're confusing me 😟

**Comment by wlbragg** [comment] 2016-12-15 17:21
@zakalawe will do, let us know when thing need to proceed.

@onox 
>If I am in the master branch and open the property browser, then /controls/engines/active-engine is an int.

Interesting, then it is more than likely caused by the state overlay code.
But now your confusing me, I don't have a `/controls/engines/active-engine` (int) in master?
Here it is in the state overlay branch (does the same think on the j3cub).
![screenshot - 12152016 - 11 03 06 am](https://cloud.githubusercontent.com/assets/11069680/21234512/86a1a4e8-c2b8-11e6-9a06-697bd980d083.jpg)
and in master I don't have it at all?
![screenshot - 12152016 - 11 15 22 am](https://cloud.githubusercontent.com/assets/11069680/21234531/996f60c4-c2b8-11e6-8f64-ed362acb0349.jpg)

**Comment by onox** [comment] 2016-12-15 22:36
This is what I have:

![fgfs-screen-017](https://cloud.githubusercontent.com/assets/3361585/21244745/47868d16-c31f-11e6-96c4-77a7b9917e6d.png)

**Comment by wlbragg** [comment] 2016-12-17 06:38
OK folks, I think I have a much better understanding of this and how to use it. First let me say in the context of this issue we will be using a few standard state flags linked to the launcher predefined agreed upon states. Like approach, parking, etc. We will piggyback on the state that the launcher sets up and adjust our overlays to make the aircraft behave accordingly at startup.
Now with that said, the exciting part to me is the ability to easily create our own developer decided states and eventually a save resume state manager.
To give you an idea of what I am talking about, try using --state=approach or --state=hanger as a flag in the qt launcher settings/additional options or the command line. Don't choose Parking or the "On final approach" options in location.
These two states are set up to start you either running and in a stable glide slope (needs a bit of throttle after startup) on approach, flaps down, to KEQA (--state=approach) or sitting at a parking spot of my choosing, running with the brakes on ready to go (--state=hanger). These are examples of how easy it is going to be to set up states. They actually override whatever location you choose at startup.
Now if we were using the Parking or "On final approach" options we would of course not set location in the overlays.. The nasal portion of this in c172p.nas (at least the passing of overlay params to local params will not be necessary once James irons out a way to tell the sim that a state is being called and not to overwrite it with saved data.
I think for testing I might create the following states

parking = use the Parking option in the QT launcher under location and set the aircraft up in state appropriate for that instance (cold, dark?). 

approach = "On final approach" option n the QT launcher under location and set the aircraft up in state appropriate for that instance.

running =  use the Parking option in the QT launcher under location and set the aircraft up in state appropriate for that instance but running and ready to go?

waterlanding = set the aircraft up in a final approach state configured with pontoons, ready for a water landing at a lake of our choice. Any want to suggest a cool lake?

Or what? Anyone have any ideas?

**Comment by wlbragg** [comment] 2016-12-17 21:15
https://sourceforge.net/p/flightgear/flightgear/ci/next/tree/src/Main/options.cxx#l1602
For reference.

**Comment by wlbragg** [comment] 2016-12-19 01:15
Added more states to play around with and test things.
approach, parking, hanger, water and cruise.
Interesting stuff going on behind the scenes though.

Variables using the flags in the QT launcher are either "On final..." or "Parking".
Combining them with their counterparts of -state=parking or --state=approach gives you what you might expect from those combinations.

Now the weird stuff. 

QT launcher on "On final..." combined with -state=parking - falls out of the sky because -state=parking settings of no airspeed and brakes on and no flaps take precedence.

**Comment by wlbragg** [comment] 2016-12-19 01:29
Now it is pretty much a waiting game. Waiting for James to dig into the underlying c++ code and making it do what we want.

**Comment by wlbragg** [comment] 2016-12-20 16:54
@onox or @gilbertohasnofb 

~~~xml
<!-- The bushkit variants: default/26"/36"/pontoons/amphibious/skis -->
            <variant alias="/fdm/jsbsim/bushkit"/>
~~~
What is this used for? It's in c172p-set.xml

**Comment by onox** [comment] 2016-12-20 18:01
`/sim/model/variant` is defined in the [multiplayer protocol](http://wiki.flightgear.org/Multiplayer_protocol). See a7c2796

**Comment by onox** [comment] 2016-12-20 18:02
So to answer your question: so we could use `/sim/multiplay/generic/int[9]` for something else.

**Comment by onox** [comment] 2018-02-12 21:07
@wlbragg This issue can be closed? State support is being addressed in other issues?

**Comment by wlbragg** [comment] 2018-02-13 02:06
Yes, I closed another one too. Appears we had a few of them floating around. I'd like to be able to reference these closed ones however because they all contain some useful information.

**Closed by wlbragg** 2018-02-13 02:06 UTC
Labels: help wanted, high priority
