### ISSUE TITLE
Improve connection between wing and pillar

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1080] opened 2018-05-06 04:16 UTC
See picture here: 
![_c203651 resized rotated](https://user-images.githubusercontent.com/423703/39669750-728980ee-5127-11e8-8f7f-0a4f25d2f047.JPG)

1. The connection between wing and pillar should more smooth. I think it is now missing something.

2. Add a L-shaped pipe, I assuming it is used for airflow intake to fuel tank.

3. Ring for tie-down should be a circle shape

![_c203653 resized](https://user-images.githubusercontent.com/423703/39669762-da5a86dc-5127-11e8-9060-cb732f8e83f7.JPG)

Note: I took photos to a *C172R* at 2018 Zhengzhou Airshow, but it is very similar exterior.

**Comment by gilbertohasnofb** [comment] 2018-05-06 11:46
@tonghuix I can confirm that the model P also has a smoother connector to the wing in all my reference photos. Concerning the L-shaped pipe, could you try to find out if this is present on both wings? Your images above clearly show it's on the left wing, but is there one on the right as well?

**Comment by tonghuix** [comment] 2018-05-06 16:44
This L-shaped pipe called '*overflow vent line*', here is more explanation https://aviation.stackexchange.com/questions/5159/what-could-cause-uneven-fuel-levels-in-a-cessna-172

Here a picture from POH:
![11](https://user-images.githubusercontent.com/423703/39675586-bd690a7c-518f-11e8-9abe-e673ffdfe954.png)

**Comment by gilbertohasnofb** [comment] 2018-05-06 16:48
@tonghuix thanks but can you help us figure out if it is located on both wings or just the left one? All pictures I've seen, including in the link you gave above, are from the left wing.

**Comment by tonghuix** [comment] 2018-05-06 16:49
@gilbertohasnofb Left only!!

**Comment by gilbertohasnofb** [comment] 2018-05-06 16:51
Great, thanks!

**Comment by tonghuix** [comment] 2018-05-07 23:41
Hi I don't think this fixes very well. Please reopen it.

Marker 1 should as smooth as marker 2:

![fgfs-screen-515](https://user-images.githubusercontent.com/423703/39730256-269303f0-5293-11e8-940b-6bfcb85e83f3.png)

Inner view,  please compare with photo.

![fgfs-screen-516](https://user-images.githubusercontent.com/423703/39730272-428ae230-5293-11e8-9c17-d1eb07ac01d5.png)

**Comment by wlbragg** [comment] 2018-05-08 00:54
@tonghuix I'm afraid your going to have to explain this better as to what you think is wrong.Is it the new portion (top piece) that you think is not as smooth as the old portion (bottom piece)?

**Comment by wlbragg** [comment] 2018-05-08 06:38
@tonghuix that doesn't look correct. The top picture shows the smoothness setting is too high. The bottom picture I can tell you extended it farther down the strut (which looks more like the image you provided) but now it partially covers the eye bolt. It also looks like the two halves settings don't match. I'm not sure how you put that together or where you "cut" from, but you can't just cut and past two different pieced from two different objects together like that and expect consistent results.
I agree that the connector part needs to be wider and to match the image it would also need to extend farther down the strut. I went ahead and made it wider but I am still reluctant to attempt to edit what I id and extend it down the strut.
Tomorrow I will pull your work and look at it closer and see if I can possible use it.
Here is the width change I made. I haven't pushed it yet.
![fgfs-screen-003](https://user-images.githubusercontent.com/11069680/39741705-8c97006c-5260-11e8-8e89-b90140902a53.png)
![fgfs-screen-004](https://user-images.githubusercontent.com/11069680/39741706-8caf9366-5260-11e8-8fc0-cfc4abcb0fe7.png)
![Uploading fgfs-screen-005.png…]()

**Comment by wlbragg** [comment] 2018-05-08 06:48
@tonghuix If I am looking at your work objectively, the outside (bottom image) is closer to matching the real images per what you pasted. But the inside (top image) is not any different that what I did, only the setting is too smooth. That is what I meant by the two halves don't match.

**Comment by tonghuix** [comment] 2018-05-08 07:34
Yep, that is correct, I just copy and paste 2 to 1: 

![fgfs-screen-515](https://user-images.githubusercontent.com/423703/39743973-4175ca26-52d5-11e8-8f8d-f9fa5cba07cd.png)

**Comment by gilbertohasnofb** [comment] 2018-05-08 09:29
@tonghuix why is the wing connector that you created in Blender looking very metallic in your pictures? Shouldn't it match the rest of the wing in colour and reflection?

**Comment by tonghuix** [comment] 2018-05-08 10:58
I don't know, maybe the UV problem? I don't know how to deal with UV, so please help me for that.

**Comment by wlbragg** [comment] 2018-05-08 15:09
@tonghuix After looking at that piece of mesh, it is a better choice that what I used, especially after a few slight modifications, it will fit and work perfectly. Would you mind letting me go ahead and make these changed in another PR? That way I can rest assured it retains all the correct settings.

**Comment by gilbertohasnofb** [comment] 2018-05-08 15:17
> Would you mind letting me go ahead and make these changed in another PR? 

I also think that could be a good idea, so that you can take care of the material UV-map and reflections as well (some of it looks very shiny in @tonghuix screenies above). If you end up doing that, then don't forget that he also raised the trim wheel indicator and made modifications to the wheels, though you must check the latter one.

**Comment by tonghuix** [comment] 2018-05-08 16:04
Okay, but please do confirm fix the issue.

**Comment by gilbertohasnofb** [comment] 2018-05-08 17:01
@wlbragg can I propose something? What if we open a PR just to fix this and the trim position, then after we merge it we freeze all exterior improvements for a while and go back to work on the interior? People can of course still report exterior issues but we will tackle them later ourselves.

If you agree, then I would be able to test and merge this later tonight.

**Comment by wlbragg** [comment] 2018-05-08 19:01
@tonghuix here is something I thing you need to be aware of. It's OK to use or copy other pieces of mesh to fix or make something new. But you have to be aware of thing like the UV mapping, material mapping, smoothness setting, did the normals get corrupted, does it need to be affected by the livery, does it now need to be a new object or part of a different object or can it stay as the same object, does it need a different effect definition. There are several things to be conscious of as you do this type of modification. If you don't deal with those issues as you go, then you are doing it wrong and creating more work for someone else to fix later, understand? 
Using this piece of mesh for an example,
it now needs to be re-uv-mapped as it is mapped to the wrong part of the texture...
![wingc](https://user-images.githubusercontent.com/11069680/39775887-c382dd26-52c4-11e8-96c9-9abc94ff5fa5.jpg)
The normal got corrupted...
![wingc2](https://user-images.githubusercontent.com/11069680/39775909-d9ae9928-52c4-11e8-8637-92101cdcb044.jpg)
In this case the material setting stays the same and the object "fuselage" stays the same, but it could have just as easily needed to be a new object with its own unique texture, material setting and effects definition. Also in this case the livery has no effect on this area but it potentially could have. 
A real big issue and one of the hardest to deal with is the material settings. You have to be very careful if adding (joining) one piece of mesh to another that you aren't introducing a second material setting. That can be a real problem. Also appending on object from one blend to use in another blend that you don't introduce unwanted textures and material settings to the blend. I've been working a lot with Blender now for a year or more and I still don't completely understand how to effectively handle material settings as when assigned to textures. It is one of the most frustrating application issues I have ever encountered in my 40+ years of programming and application experiences. It doesn't appear to be well documented and in my opinion is full of bugs. Either that or our blend has some hidden issues. I have to be very careful when dealing with our material settings. It is easy to get Blender completely confused as to what material settings to use on what objects and texture combinations. On many occasions I have lost material assignments to multiple objects because I tried to set up a new material setting. I've yet to understand the cause only the effect.

Maybe you are already aware of all these potential issues, but I thought I would bring it up just in case you weren't aware of it.

**Closed** 2018-05-08 21:42 UTC
Labels: 3D model, enhancement
