### ISSUE TITLE
Magnetos switch to both when toggling walker outside

### ISSUE THREAD

**Issue by kentrosaur** [c172p-team/c172p-detailed#899] opened 2017-02-12 22:26 UTC
1.) start up fgfs with c172p, start going through checklists note magnetos are set to off
2.) toggle walker ouside ( complete exterior checklist if desired )
3.) toggle walker inside, note magnetos are now set to both

This is bad, as if you perturb the prop on exterior check, the engine may start.  I'm not sure if it's the re-entry or exit which changes the magneto state.

**Comment by gilbertohasnofb** [comment] 2017-02-12 23:00
@kentrosaur verified, nice catch. To anyone trying to reproduce and solve this issue, it has one caveat: just having magentos off and toggling the walker via the menu does not cause the problem to appear; neither does going through the pre-flight checklist and toggling the walker via the checklist itself. The only way I could reproduce it is by going through the pre-flight checklist, then when reaching the last item I would toggle the walker via the menu. This will case the magnetos to immediately move to the BOTH position.

Now, I am completely at lost on why this might be happening, does anyone else have any idea(s) on how to approach this?

**Comment by condab** [comment] 2017-04-05 11:35
Yes! I do! Lucky I randomly stumbled upon this, I'm supposed to be looking for something else. 

It's because when you are in walker view, you are given 'wasd' controls. Note that while in Walker view, I've found that walking backward (using 's' key) is still connected to the engine start keyboard shortcut ('s' key). I've found that if you walk backward, then get back in the cockpit view, the magnetos are now both, because this is what would happen if you were to press 's' normally in cockpit view but cancel whilst starting. So; going from [OFF] to [START] and then cancelling [START] returns the key to [BOTH]. 

To my belief, this doesn't actually initiate engine start while in walker mode, but some code has slipped through which still allows magnetos to be set. (Please confirm, I can't be bothered to check at this moment.)

EDIT: confirmed just now. You can see this by moving your walker INSIDE the cockpit and watching the key as you press 's'.

**Comment by gilbertohasnofb** [comment] 2017-04-05 14:58
@condab that's some brilliant troubleshooting, thanks a lot for the input. Now i wonder what's the best solution for this. Should this be addressed in the aircraft development level or in FG core code level? Surely we could add some conditional for the magnetos to work only if in an internal view, but this looks a bit inelegant to me as all other shortcuts do work from an external view.

**Comment by condab** [comment] 2017-04-06 02:24
I'm glad I could help out. I should try and browse GitHub more and work as a bug spotter, haha.

I know nothing about the code, nor am I a developer etc. but rather than making magnetos only work in internal views, which brings up a problem which you stated, we could exclude ALL aircraft controls whilst in views: walker; walker orbit. 

This makes sense, for if you are outside the aircraft in the real world, you cannot access controls which are inside the aircraft. The only problem that I could imagine arises from this is a lack on continuity across all walker-included aircraft in FG, as others will still allow control whilst in walker views. This is a minor sacrifice in my opinion.

If all else fails, [exclude all aircraft controls while in walker view] could be a toggle option in the 'Aircraft Options' panel. Again, I don't know if either of these options are great or doable because I know nothing about the code.

**Comment by gilbertohasnofb** [comment] 2017-04-06 14:54
> I figure that this now removes association with 'checklists' and so the tag should be removed.

:+1: I just tested it in the sim and indeed this has nothing to do with the checklists

**Comment by hbeni** [comment] 2017-12-16 20:42
I proposed a fix in the [c182s / PR #214](https://github.com/HHS81/c182s/pull/214) repository.
It fixes the issue by checking for the two walker views and in my opinion this is an important thing:
i for example go (in walker view) to the open cockpit door, peek into the interior, engange master switch, avionics and pitot-heat for the preflight. I would find it disturbing to actually have to "get into the seat" for doing this.

**Closed** 2018-02-10 17:03 UTC
Labels: animations (XML), bug
