### ISSUE TITLE
Message: Multiplayer packet truncated prop  id: 10308: sim/multiplay/generic/int[8]

### ISSUE THREAD

**Issue by callahanp** [c172p-team/c172p-detailed#1064] opened 2018-04-18 14:41 UTC
When starting flightgear with the default aircraft and then attaching
to a multiplayer server, the console is flooded with messages:
Multiplayer packet truncated prop id: 10308:sim/multiplay/generic/int[8]

It appears there are too many items being sent out using the V1_1 protocol, and multiplaymgr.cxx is just tossing out anything after 10307	sim/multiplay/generic/int[7], while still sending the message.  However  in the console  EVERY time a position packet is sent the message repeats. That causes some misery when trying to figure out other multiplayer problems with the C172 as the console output from other things just gets swamped.

There's a couple of things that could be done, both in the Aircraft data and in SG_LOG module (count repeated similar messages and print the count and the message when a different message is to be logged.  I'll propose that on fg-devel.

Bug Details:

In FGMultiplayMgr::SendMyPosition Line 1538 and 1582 can produce this
message.  In this case, it's line 1538 that is the culprit.  It's
in a loop that is processing motionInfo.properties and the message repeats until multiplay is suspended or flightgear exits.

Personally:

I'd like to find out more about how the data in the Aircraft is processed to produce the list of data to be included in the "Position" message.

I'm just getting started wading through flightgear's codebase and so far have just from command line through holding short on the runway.  I've also examined the multiplaymgr.cxx. and http://wiki.flightgear.org/Multiplayer_protocol#First_part.  

I'm willing to work on this with the C172 team on this issue.

Pointers to stuff to read beyond what's on the flightgear wiki about aircraft and MP would help.

Also do you have other communication channel I could join devoted to this aircraft?  

-Pat
 N4217P - I wish that were a real aircraft. 
 Contact me through github, flightgear - mailing list, wiki, forum, maybe irc)

[MPPositionPacketDump.txt](https://github.com/c172p-team/c172p-detailed/files/1924342/MPPositionPacketDump.txt)

**Comment by legoboyvdlp** [comment] 2018-04-18 14:48
This aircraft requires the new multiplayer protocol introduced in 2017.2 -> you can enable it in multiplayer settings.

**Comment by legoboyvdlp** [comment] 2018-04-18 17:27
If you set the option to the new protocol, only new protocol traffic can see you. If not, all traffic can see you.

I thought it was protocol v2 by default?

It is shown in multiplayer menu in-sim, but the launcher is designed not to be cluttered with options as far as I know.

**Comment by onox** [comment] 2018-04-18 22:36
Duplicate of #1041

**Closed by onox** 2018-04-18 22:36 UTC

**Comment by onox** [comment] 2018-04-18 22:50
> I thought it was protocol v2 by default?

The default has been changed to v2 in 2018.2 in FGDATA. #1011 will take advantage of protocol v2 and display a warning dialog if people use the old protocol.

> Is setting the protocol to 2017.x really a problem?

Not really. The problem is that the server should enforce that everybody follows the same rules (all protocol 2 or all protocol 1). (I'll try not to rant too much about fgms) That gives only short-term pain for people who haven't upgraded yet.

> Who uses flightgear before 2017.x?

People running FG on potatoes.

> If you use the new protocol and I don't in 2017x or greater, do I see you?

AFAIK if you have a recent version of FG (2017.2+) you should see planes that use the new protocol even if you use the old protocol. But potatoes running ancient versions of FG will not. Correct me @Zaretto if I'm wrong about this.

**Comment by onox** [comment] 2018-04-18 23:02
@callahanp Thanks for reporting the issue, it shows multiple people are experiencing these messages and that we need to make sure that the plane makes it clear that v2 is required.
