### ISSUE TITLE
Idea: Update new splash screen images

### ISSUE THREAD

**Issue by tonghuix** [c172p-team/c172p-detailed#1033] opened 2018-03-29 05:10 UTC
Thanks to the exterior changes recently, the plane has improved a lot! So I suggest we could update splash screen images. 

I suggest we could make a community event at FG forum, let every try new plane and upload their screenshot for a vote.  Vote for the most welcomed screenshots for next release.

**Comment by onox** [comment] 2018-03-29 06:32
Duplicate of #967

**Closed by onox** 2018-03-29 06:32 UTC
