### ISSUE TITLE
damage repair should fix everything, including flipping a crashed craft back onto its landing gear

### ISSUE THREAD

**Issue by wkitty42** [c172p-team/c172p-detailed#1049] opened 2018-04-06 19:31 UTC
i've crashed a few times with damage on and complex procedures and failures on... when i click the damage repair option, everything is apparently fixed and a tool tip pops up that says the battery is fully charged but the craft is still upside down or otherwise not on its gear...

damage repair should fix everything including flipping the craft back over onto its gear... this flipping over is what is not being done...

**Comment by gilbertohasnofb** [comment] 2018-04-06 19:38
This is a duplicate of https://github.com/c172p-team/c172p-detailed/issues/308

**Closed by gilbertohasnofb** 2018-04-06 19:38 UTC
Labels: duplicate

**Comment by wkitty42** [comment] 2018-04-06 19:41
durn it :(  ok...
