### ISSUE TITLE
Autopilot seems buggy

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#769] opened 2016-05-23 21:49 UTC
Autopilot seems buggy

@wlbragg wrote:

> Also for the autopilot, I'm unclear on its behavior. It appears to be 'off" by default until you hit the AP button, but then you can't turn off the digital display by hitting it again, how does that work?

I wrote:

> About the AP, it indeed looks buggy... sometimes by clicking several times on the main arm/disarm button, I manage to get the display dark again, but not always.

**Comment by wlbragg** [comment] 2016-05-23 21:53
One issue is

hit AP, hit it again, pull autopilot breaker, push autopilot breaker

pull autopilot breaker, wait till all AP digital display go black, push autopilot breaker

hit AP, pull autopilot breaker


Another issue I have had "every time I use it" after flying for x-time it suddenly re-configures itself and put's me into a spin that is usually catastrophic.

**Comment by gilbertohasnofb** [comment] 2016-05-23 22:05
@wlbragg yes, I can reproduce that, amazing catch! How did you find it?! It's a bit like the Konami cheat code :arrow_up: :arrow_up: :arrow_down: :arrow_down: :arrow_left: :arrow_right: :arrow_left: :arrow_right: :b: :a: , isn't it? :stuck_out_tongue_winking_eye:

**Comment by onox** [comment] 2016-05-24 04:48
This is sort of a duplicate of #603?

**Comment by gilbertohasnofb** [comment] 2016-05-24 06:14
Sort of yes, I suppose. What do you recommend, shall we move all these comments to that issue there and close this one?

**Comment by wlbragg** [comment] 2016-05-24 18:15
>It's a bit like the Konami cheat code

Yeah, I thought it really strange. I found it because I was trying to see if there was any way to completely remove power from the Autopilot. I ended up at the breaker, that is when I noticed it had a very strange behavior.

**Closed** 2018-03-01 04:08 UTC
Labels: animations (XML), bug, duplicate
